# Generated by Django 6.0.5 on 2026-05-25 10:58

import apps.jobs.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0009_alter_enterpriseprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('WATER', 'Water Industry'), ('CONSTRUCTION', 'Construction & BTP'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & Commerce'), ('ENERGY', 'Energy & Oil'), ('AGRICULTURE', 'Agriculture'), ('TRANSPORT', 'Transport & Logistics'), ('OTHER', 'Other')], max_length=50)),
                ('role', models.CharField(choices=[('GENERAL_PRACTITIONER', 'General Practitioner'), ('SPECIALIST_DOCTOR', 'Specialist Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('WEB_DEVELOPER', 'Web Developer'), ('MOBILE_DEVELOPER', 'Mobile Developer'), ('DATA_SCIENTIST', 'Data Scientist'), ('IT_PROJECT_MANAGER', 'IT Project Manager'), ('SYSTEM_ADMINISTRATOR', 'System Administrator'), ('SALES_REPRESENTATIVE', 'Sales Representative'), ('SALES_DIRECTOR', 'Sales Director'), ('PRODUCT_MANAGER', 'Product Manager'), ('PRIMARY_TEACHER', 'Primary School Teacher'), ('HIGH_SCHOOL_TEACHER', 'High School Teacher'), ('TRAINER', 'Trainer / Instructor'), ('CIVIL_ENGINEER', 'Civil Engineer'), ('MECHANICAL_ENGINEER', 'Mechanical Engineer'), ('ARCHITECT', 'Architect'), ('ACCOUNTANT', 'Accountant'), ('FINANCIAL_ANALYST', 'Financial Analyst'), ('AUDITOR', 'Auditor'), ('COMMUNICATIONS_OFFICER', 'Communications Officer'), ('COMMUNITY_MANAGER', 'Community Manager'), ('ADMINISTRATIVE_ASSISTANT', 'Administrative Assistant'), ('HR_MANAGER', 'HR Manager'), ('GRAPHIC_DESIGNER', 'Graphic Designer'), ('UX_UI_DESIGNER', 'UX/UI Designer'), ('VIDEO_EDITOR', 'Video Editor'), ('OTHER', 'Other')], max_length=50)),
                ('wilaya', models.CharField(choices=[('adrar', 'Adrar'), ('chlef', 'Chlef'), ('laghouat', 'Laghouat'), ('oum_el_bouaghi', 'Oum El Bouaghi'), ('batna', 'Batna'), ('bejaia', 'Béjaïa'), ('biskra', 'Biskra'), ('bechar', 'Béchar'), ('blida', 'Blida'), ('bouira', 'Bouira'), ('tamanrasset', 'Tamanrasset'), ('tebessa', 'Tébessa'), ('tlemcen', 'Tlemcen'), ('tiaret', 'Tiaret'), ('tizi_ouzou', 'Tizi Ouzou'), ('alger', 'Alger'), ('djelfa', 'Djelfa'), ('jijel', 'Jijel'), ('setif', 'Sétif'), ('saida', 'Saïda'), ('skikda', 'Skikda'), ('sidi_bel_abbes', 'Sidi Bel Abbès'), ('annaba', 'Annaba'), ('guelma', 'Guelma'), ('constantine', 'Constantine'), ('medea', 'Médéa'), ('mostaganem', 'Mostaganem'), ('msila', "M'Sila"), ('mascara', 'Mascara'), ('ouargla', 'Ouargla'), ('oran', 'Oran'), ('el_bayadh', 'El Bayadh'), ('illizi', 'Illizi'), ('bordj_bou_arreridj', 'Bordj Bou Arréridj'), ('boumerdes', 'Boumerdès'), ('el_tarf', 'El Tarf'), ('tindouf', 'Tindouf'), ('tissemsilt', 'Tissemsilt'), ('el_oued', 'El Oued'), ('khenchela', 'Khenchela'), ('souk_ahras', 'Souk Ahras'), ('tipaza', 'Tipaza'), ('mila', 'Mila'), ('ain_defla', 'Aïn Defla'), ('naama', 'Naâma'), ('ain_temouchent', 'Aïn Témouchent'), ('ghardaia', 'Ghardaïa'), ('relizane', 'Relizane')], max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50)),
                ('experience_required', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('applicants', models.PositiveIntegerField(default=0)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='profiles.enterpriseprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='announcements', to='profiles.skill')),
            ],
            options={
                'db_table': 'jobs_job_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=apps.jobs.utils.upload_resume_applications)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.announcement')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.individualprofile')),
            ],
            options={
                'db_table': 'jobs_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
