# Generated by Django 6.0.3 on 2026-04-08 23:14

import apps.profiles.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('company_name', models.CharField(max_length=200)),
                ('wilaya', models.CharField(blank=True, choices=[('adrar', '01 - Adrar'), ('chlef', '02 - Chlef'), ('laghouat', '03 - Laghouat'), ('oum_el_bouaghi', '04 - Oum El Bouaghi'), ('batna', '05 - Batna'), ('bejaia', '06 - Béjaïa'), ('biskra', '07 - Biskra'), ('bechar', '08 - Béchar'), ('blida', '09 - Blida'), ('bouira', '10 - Bouira'), ('tamanrasset', '11 - Tamanrasset'), ('tebessa', '12 - Tébessa'), ('tlemcen', '13 - Tlemcen'), ('tiaret', '14 - Tiaret'), ('tizi_ouzou', '15 - Tizi Ouzou'), ('alger', '16 - Alger'), ('djelfa', '17 - Djelfa'), ('jijel', '18 - Jijel'), ('setif', '19 - Sétif'), ('saida', '20 - Saïda'), ('skikda', '21 - Skikda'), ('sidi_bel_abbes', '22 - Sidi Bel Abbès'), ('annaba', '23 - Annaba'), ('guelma', '24 - Guelma'), ('constantine', '25 - Constantine'), ('medea', '26 - Médéa'), ('mostaganem', '27 - Mostaganem'), ('msila', "28 - M'Sila"), ('mascara', '29 - Mascara'), ('ouargla', '30 - Ouargla'), ('oran', '31 - Oran'), ('el_bayadh', '32 - El Bayadh'), ('illizi', '33 - Illizi'), ('bordj_bou_arreridj', '34 - Bordj Bou Arréridj'), ('boumerdes', '35 - Boumerdès'), ('el_tarf', '36 - El Tarf'), ('tindouf', '37 - Tindouf'), ('tissemsilt', '38 - Tissemsilt'), ('el_oued', '39 - El Oued'), ('khenchela', '40 - Khenchela'), ('souk_ahras', '41 - Souk Ahras'), ('tipaza', '42 - Tipaza'), ('mila', '43 - Mila'), ('ain_defla', '44 - Aïn Defla'), ('naama', '45 - Naâma'), ('ain_temouchent', '46 - Aïn Témouchent'), ('ghardaia', '47 - Ghardaïa'), ('relizane', '48 - Relizane')], max_length=50)),
                ('industry', models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('CONSTRUCTION', 'Construction & BTP'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & Commerce'), ('ENERGY', 'Energy & Oil'), ('AGRICULTURE', 'Agriculture'), ('TRANSPORT', 'Transport & Logistics'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('company_size', models.CharField(blank=True, choices=[('STARTUP', '1–10 employees'), ('SMALL', '11–50 employees'), ('MEDIUM', '51–200 employees'), ('LARGE', '200+ employees')], max_length=10)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Enterprise Profile',
                'verbose_name_plural': 'Enterprise Profiles',
                'db_table': 'profiles_enterprise',
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.profile')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('wilaya', models.CharField(choices=[('adrar', '01 - Adrar'), ('chlef', '02 - Chlef'), ('laghouat', '03 - Laghouat'), ('oum_el_bouaghi', '04 - Oum El Bouaghi'), ('batna', '05 - Batna'), ('bejaia', '06 - Béjaïa'), ('biskra', '07 - Biskra'), ('bechar', '08 - Béchar'), ('blida', '09 - Blida'), ('bouira', '10 - Bouira'), ('tamanrasset', '11 - Tamanrasset'), ('tebessa', '12 - Tébessa'), ('tlemcen', '13 - Tlemcen'), ('tiaret', '14 - Tiaret'), ('tizi_ouzou', '15 - Tizi Ouzou'), ('alger', '16 - Alger'), ('djelfa', '17 - Djelfa'), ('jijel', '18 - Jijel'), ('setif', '19 - Sétif'), ('saida', '20 - Saïda'), ('skikda', '21 - Skikda'), ('sidi_bel_abbes', '22 - Sidi Bel Abbès'), ('annaba', '23 - Annaba'), ('guelma', '24 - Guelma'), ('constantine', '25 - Constantine'), ('medea', '26 - Médéa'), ('mostaganem', '27 - Mostaganem'), ('msila', "28 - M'Sila"), ('mascara', '29 - Mascara'), ('ouargla', '30 - Ouargla'), ('oran', '31 - Oran'), ('el_bayadh', '32 - El Bayadh'), ('illizi', '33 - Illizi'), ('bordj_bou_arreridj', '34 - Bordj Bou Arréridj'), ('boumerdes', '35 - Boumerdès'), ('el_tarf', '36 - El Tarf'), ('tindouf', '37 - Tindouf'), ('tissemsilt', '38 - Tissemsilt'), ('el_oued', '39 - El Oued'), ('khenchela', '40 - Khenchela'), ('souk_ahras', '41 - Souk Ahras'), ('tipaza', '42 - Tipaza'), ('mila', '43 - Mila'), ('ain_defla', '44 - Aïn Defla'), ('naama', '45 - Naâma'), ('ain_temouchent', '46 - Aïn Témouchent'), ('ghardaia', '47 - Ghardaïa'), ('relizane', '48 - Relizane')], default='', max_length=50)),
                ('title', models.CharField(blank=True, help_text="'Full Stack Developer'", max_length=150)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, help_text='Total years of professional experience')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available Now'), ('OPEN', 'Open to Opportunities'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=apps.profiles.utils.resume_upload_path)),
            ],
            options={
                'verbose_name': 'Individual Profile',
                'verbose_name_plural': 'Individual Profiles',
                'db_table': 'profiles_individual',
            },
            bases=('accounts.profile',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('DESIGN', 'Design'), ('MARKETING', 'Marketing'), ('MANAGEMENT', 'Management'), ('FINANCE', 'Finance'), ('ENGINEERING', 'Engineering'), ('DATA', 'Data & Analytics'), ('LANGUAGES', 'Languages'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
            options={
                'db_table': 'profiles_skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text="'Bachelor of Science', 'Master', 'Licence'", max_length=150)),
                ('field', models.CharField(help_text="'Computer Science', 'Civil Engineering'", max_length=150)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if still studying', null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.individualprofile')),
            ],
            options={
                'db_table': 'profiles_education',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, help_text='Link to live project, GitHub repo, or Behance page')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.profiles.utils.portfolio_image_upload_path)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.individualprofile')),
            ],
            options={
                'db_table': 'profiles_portfolio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current position', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='profiles.individualprofile')),
            ],
            options={
                'db_table': 'profiles_work_experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=15)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.individualprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='profiles.skill')),
            ],
            options={
                'db_table': 'profiles_user_skills',
                'unique_together': {('individual', 'skill')},
            },
        ),
    ]
