# Generated by Django 6.0.3 on 2026-04-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprofile',
            name='years_experience',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='years_experience',
        ),
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('STARTUP', 'Start-Up'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('adrar', 'Adrar'), ('chlef', 'Chlef'), ('laghouat', 'Laghouat'), ('oum_el_bouaghi', 'Oum El Bouaghi'), ('batna', 'Batna'), ('bejaia', 'Béjaïa'), ('biskra', 'Biskra'), ('bechar', 'Béchar'), ('blida', 'Blida'), ('bouira', 'Bouira'), ('tamanrasset', 'Tamanrasset'), ('tebessa', 'Tébessa'), ('tlemcen', 'Tlemcen'), ('tiaret', 'Tiaret'), ('tizi_ouzou', 'Tizi Ouzou'), ('alger', 'Alger'), ('djelfa', 'Djelfa'), ('jijel', 'Jijel'), ('setif', 'Sétif'), ('saida', 'Saïda'), ('skikda', 'Skikda'), ('sidi_bel_abbes', 'Sidi Bel Abbès'), ('annaba', 'Annaba'), ('guelma', 'Guelma'), ('constantine', 'Constantine'), ('medea', 'Médéa'), ('mostaganem', 'Mostaganem'), ('msila', "M'Sila"), ('mascara', 'Mascara'), ('ouargla', 'Ouargla'), ('oran', 'Oran'), ('el_bayadh', 'El Bayadh'), ('illizi', 'Illizi'), ('bordj_bou_arreridj', 'Bordj Bou Arréridj'), ('boumerdes', 'Boumerdès'), ('el_tarf', 'El Tarf'), ('tindouf', 'Tindouf'), ('tissemsilt', 'Tissemsilt'), ('el_oued', 'El Oued'), ('khenchela', 'Khenchela'), ('souk_ahras', 'Souk Ahras'), ('tipaza', 'Tipaza'), ('mila', 'Mila'), ('ain_defla', 'Aïn Defla'), ('naama', 'Naâma'), ('ain_temouchent', 'Aïn Témouchent'), ('ghardaia', 'Ghardaïa'), ('relizane', 'Relizane')], max_length=50),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='wilaya',
            field=models.CharField(choices=[('adrar', 'Adrar'), ('chlef', 'Chlef'), ('laghouat', 'Laghouat'), ('oum_el_bouaghi', 'Oum El Bouaghi'), ('batna', 'Batna'), ('bejaia', 'Béjaïa'), ('biskra', 'Biskra'), ('bechar', 'Béchar'), ('blida', 'Blida'), ('bouira', 'Bouira'), ('tamanrasset', 'Tamanrasset'), ('tebessa', 'Tébessa'), ('tlemcen', 'Tlemcen'), ('tiaret', 'Tiaret'), ('tizi_ouzou', 'Tizi Ouzou'), ('alger', 'Alger'), ('djelfa', 'Djelfa'), ('jijel', 'Jijel'), ('setif', 'Sétif'), ('saida', 'Saïda'), ('skikda', 'Skikda'), ('sidi_bel_abbes', 'Sidi Bel Abbès'), ('annaba', 'Annaba'), ('guelma', 'Guelma'), ('constantine', 'Constantine'), ('medea', 'Médéa'), ('mostaganem', 'Mostaganem'), ('msila', "M'Sila"), ('mascara', 'Mascara'), ('ouargla', 'Ouargla'), ('oran', 'Oran'), ('el_bayadh', 'El Bayadh'), ('illizi', 'Illizi'), ('bordj_bou_arreridj', 'Bordj Bou Arréridj'), ('boumerdes', 'Boumerdès'), ('el_tarf', 'El Tarf'), ('tindouf', 'Tindouf'), ('tissemsilt', 'Tissemsilt'), ('el_oued', 'El Oued'), ('khenchela', 'Khenchela'), ('souk_ahras', 'Souk Ahras'), ('tipaza', 'Tipaza'), ('mila', 'Mila'), ('ain_defla', 'Aïn Defla'), ('naama', 'Naâma'), ('ain_temouchent', 'Aïn Témouchent'), ('ghardaia', 'Ghardaïa'), ('relizane', 'Relizane')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('BEHANCE', 'Behance'), ('DRIBBBLE', 'Dribbble'), ('TWITTER', 'Twitter / X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('WEBSITE', 'Personal Website')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.profile')),
            ],
            options={
                'db_table': 'profiles_social_links',
                'ordering': ['platform'],
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
