# Generated by Django 6.0.3 on 2026-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_individualprofile_years_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='years_experiance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
