# Generated by Django 6.0.3 on 2026-04-30 15:39

import apps.profiles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_individualprofile_years_experiance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={},
        ),
        migrations.RenameField(
            model_name='individualprofile',
            old_name='years_experiance',
            new_name='years_experience',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='enterpriseprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='individualprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='register',
            field=models.FileField(blank=True, null=True, upload_to=apps.profiles.utils.enterprise_register_upload_path),
        ),
        migrations.AddField(
            model_name='enterpriseprofile',
            name='specialty',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('CONSTRUCTION', 'Construction & BTP'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & Commerce'), ('ENERGY', 'Energy & Oil'), ('AGRICULTURE', 'Agriculture'), ('TRANSPORT', 'Transport & Logistics'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='professional_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='field',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('BEHANCE', 'Behance'), ('DRIBBBLE', 'Dribbble'), ('TWITTER', 'Twitter / X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('WEBSITE', 'Personal Website')], default='', max_length=20),
        ),
    ]
