# Generated by Django 6.0.3 on 2026-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_education_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
