# Generated by Django 6.0.3 on 2026-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_enterpriseprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseprofile',
            name='specialty',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FINANCE', 'Finance & Banking'), ('WATER', 'Water Industry'), ('CONSTRUCTION', 'Construction & BTP'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & Commerce'), ('ENERGY', 'Energy & Oil'), ('AGRICULTURE', 'Agriculture'), ('TRANSPORT', 'Transport & Logistics'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
