# Generated by Django 6.0.3 on 2026-05-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_enterpriseprofile_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterpriseprofile',
            old_name='city',
            new_name='address',
        ),
    ]
