# Generated by Django 6.0.5 on 2026-05-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_city_enterpriseprofile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterpriseprofile',
            old_name='specialty',
            new_name='industry',
        ),
        migrations.RenameField(
            model_name='individualprofile',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='role',
            new_name='job_role',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('TWITTER', 'Twitter / X'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('WEBSITE', 'Personal Website')], default='', max_length=20),
        ),
    ]
